name: Run Samplifi on Dataset

on:
  workflow_dispatch:
    inputs:
      dataset:
        description: 'Dataset to download and process'
        required: true

jobs:
  run-samplifi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.10'

    - name: Conda env, download dataset, run samplifi
      timeout-minutes: 180
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda env create -f environment.yml
        conda activate samplifi
        python -m pip install mirdata
        python download-mir-dataset.py --dataset "${{ github.event.inputs.dataset }}"
        python run-samplifi.py --dataset ${{ github.event.inputs.dataset }}

    # - name: Download dataset
    #   timeout-minutes: 180
    #   run: |
        
    #     conda activate samplifi
        

    # - name: Run Samplifi
    #   run: |
    #     source $(conda info --base)/etc/profile.d/conda.sh
    #     conda activate samplifi
        

    - name: Upload CSV as artifact
      uses: actions/upload-artifact@v2
      with:
        name: samplifi-output
        path: haaqi_scores.csv # Replace with the path to your CSV file

