name: Run Samplifi on a dataset
run-name: Running Samplifi against ${{ inputs.dataset }} with ${{ inputs.sample_size }} samples

on:
  workflow_dispatch:
    inputs:
      dataset:
        description: 'Dataset to download and process'
        required: true
      sample_size:
        description: 'Number of samples to test'
        required: false
        default: '250'

jobs:
  run-samplifi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Running out of disk space on git runner
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # when set to "true" but frees about 6 GB
        tool-cache: true

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.9'  # Use Python 3.9

    - name: Create and activate Conda environment
      run: |
        echo "source $(conda info --base)/etc/profile.d/conda.sh" >> ~/.bashrc
        source ~/.bashrc
        conda env create -f environment.yml
        conda activate samplifi
        python -m pip install tensorflowjs --no-deps

    - name: Download dataset
      timeout-minutes: 180
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate samplifi
        python download-mir-dataset.py --dataset "${{ github.event.inputs.dataset }}"

    - name: Run Samplifi
      timeout-minutes: 600
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate samplifi
        python run-samplifi.py --dataset ${{ github.event.inputs.dataset }} --sample-size "${{ github.event.inputs.sample_size }}" --eval-haaqi --eval-spectral --titrate

    - name: Analyze results
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate samplifi
        python analyze-results.py --file evaluation_${{ github.event.inputs.dataset }}.json --omit-f0

    - name: Upload JSON as artifact
      uses: actions/upload-artifact@v4
      with:
        name: samplifi-output
        path: evaluation_${{ github.event.inputs.dataset }}.json

    - name: Upload analysis folder as artifact
      uses: actions/upload-artifact@v4
      with:
        name: samplifi-analysis
        path: analysis